homewok2
mulla159/gb-go-step-1 pull request #2
Opened 2021-11-21 18:43 UTC by mulla159

2021-11-21 20:32 UTC, v-lozhkin requested changes

2021-11-21 20:32 UTC, v-lozhkin commented on homework2/2/main.go
> +	var circleArea, circleDiameter, circleRadius, circleLength float64
Это можно не править, но просто совет на будущее - переменные лучше объявлять как можно ближе к месту их использования. Так, при прочтении, будет понятнее, зачем они нужны. В данном случае я бы перенес объявление circleDiameter, circleRadius, circleLength к месту их вычисления

2021-11-21 20:32 UTC, v-lozhkin commented on homework2/4/main.go
> +	return number > 1
Я понимаю, что это проверка на единицу, но не совсем понятно, зачем она, если мы передаем значения в функцию в цикле от 2х :)

2021-11-21 20:32 UTC, v-lozhkin commented on homework2/4/main.go
> +func isPrime(number int) bool {
Классная идея использовать функцию!

2021-11-22 03:26 UTC, mulla159 commented on homework2/2/main.go
> +	var circleArea, circleDiameter, circleRadius, circleLength float64
согласен, поправил

2021-11-22 20:49 UTC, v-lozhkin approved these changes
Ок, можно мержить

2021-11-23 04:21 UTC, merged