homework 4
mulla159/gb-go-step-1 pull request #5
Opened 2021-12-05 19:26 UTC by mulla159

2021-12-06 08:32 UTC, v-lozhkin requested changes

2021-12-06 08:32 UTC, v-lozhkin commented on homework5/2/main.go
> +	fibNumbers := map[int]int{0: 0, 1: 1}
Идея верна, вот только не оптимизация не сработает, так как в каждом вызове функции будет свой локальный экземпляр мапы, и там всегда будут только 0 и 1 числа. 
мапа должна храниться выше скопа функции (либо как глобальная переменная, либо передавать ее в функцию как аргумент )

2021-12-06 15:15 UTC, mulla159 commented on homework5/2/main.go
> +	fibNumbers := map[int]int{0: 0, 1: 1}
поправил

2021-12-07 07:35 UTC, v-lozhkin approved these changes
Отлично, принято

2021-12-07 07:45 UTC, merged